### ISSUE TITLE
Invalid Links

### ISSUE THREAD

**Issue by eceltov** [glampert/reverse-engineering-dungeon-siege#8]
Hello, I noticed that the links to the Skrit manual are non-functional.
Could you please replace them?

They are found in the `misc/other-formats.txt` file on line 36 and onward.
For example, the Skrit technical manual link: http://scottbilas.com/files/dungeon_siege/Skrit.html

Many thanks for all the work you did on this project.

**Comment by glampert** [comment]
Hi @eceltov,

Yes, Scott Bilas' website went down a few years ago, but luckily it can still be found on the webarchive: https://web.archive.org/web/20160305051805/http://scottbilas.com/files/dungeon_siege/Skrit.html

I also have a copy of the skrit technical manual saved in this repository:
https://github.com/glampert/reverse-engineering-dungeon-siege/blob/master/source/thirdparty/gpg/docs/skrit-tech-manual.pdf

**Comment by eceltov** [comment]
Hi @glampert,

Thank you for the links.
